### ISSUE TITLE
Subtitle Filtering

### ISSUE THREAD

**Issue by phdelodder** [phdelodder/SubTools#19]
Currently there are 2 pull request and 2 issues about how to filter subtitle to get the correct one's to the user. There for I suggest a new approach : 

![subtitleselection](https://cloud.githubusercontent.com/assets/7259755/5790048/8fe7e186-9e87-11e4-98ce-05ea43b91a77.png)

This approach in the diagram is a major change to the application, to implement it would requre some changes in dev-1.0.0 to be undone and some parts needs to be rewritten. 

The yellow is a settings that can be changed in the options, there rest will be how it works!

Please give you opinion @RobinHoutevelts and @masterbreel? any one else how likes to share ...

**Comment by RobinHoutevelts** [comment]
@masterbreel heeft aangehaald in #17:
>... zou de tool niet ongeveer dit moeten doen?:
>...
>Download: ALS mogelijk: regel 1 (kwaliteit)
>Anders: download: **regel 2 (release group)**
>Anders: download enige letterlijk overeengekomen deel aflevering naam / subnaam 
>Anders: download eerste gevonden

Wouldn't it be better to put the releasegroup-rule first? Subtitles from a 480p- and 720p release are interchangeable when it's from the same releasegroup because the capture-source is the same.

By placing the "hdtv.720p" check first you greatly increase the chance that you get a match with some p2p group that doesn't sync with whatever you have.

---

@phdelodder

Here is my approach to this problem.
This is the best I could come up with in such little time.

I'd drop the "exact match" and "keyword-match" and "release group match" and "automatic download rules", ...
It's too complicated. IMO my solution is elegant ( although I'm biased :p ) and always gives optimal results.

## A quick scenario

In this section I demonstrate a way to sort subtitles based on relevance using weighted keywords.

We want to find subtitles for **showname.s01e01.720p.HDTV.x264-acme.**

This gets parsed to a **TVRelease** object that extends the abstract **Release** object:

| property     | value    | implementing interface |
| ------------ | -------- | --------- |
| show         | showname | **TVRelease**
| season       | 01       | **TVRelease**
| episode      | 01       | **TVRelease**
| tags         |          | **Release**
|              | 720p     | 
|              | HDTV     |
|              | x264     |
| releasegroup | acme     | **Release**

SubtitleProviders find these subtitles:

| id    | Subtitles |
| ----- | --------- |
| 1 | showname.s01.e01.720p.bluray.x264-oscorp            |
| 2 | showname.s01.e01.hdtv.x264-acme                     | 
| 3 | this one should work with acme                      |
| 4 | showname.s01.e01.720p.hdtv.x264-acme                |
| 5 | showname.s01.e01.720p.hdtv.x264-releasegroupyouhate |

### Defining keywords and weights

First up we have to define keywords and assign a weight.

*All the keywords can be modified in the settings*

#### Default keywords

| Keyword        | Weight |
| -------------- | ------ |
| %SHOWNAME%     | 1 |
| %SEASON%       | 1 |
| %EPISODE%      | 1 |
| %RELEASEGROUP% | 8 |

#### Default dynamic keywords
These keywords are only used when they are found in the **tags** of the **Release** object.

| Keyword | Weight |
| ------- | ------ |
| 720p    | 2 |
| 1080p   | 2 |
| hdtv    | 3 |
| bluray  | 3 |
| x264    | 2 |

#### Custom keywords
These keywords are added by the user.

| Keyword             | Weight |
| ------------------- | ------ |
| releasegroupyouhate | -99    |

### Calculating the score

Based on keywords and weights above the weights-table for **showname.s01e01.720p.HDTV.x264-acme** would look like this:

| Keyword             | Weight |
| ------------------- | ------ |
| showname            | 1 |
| s01                 | 1 |
| e01                 | 1 |
| acme                | 8 |
| releasegroupyouhate | -99 |
| 720p                | 2 |
| hdtv                | 3 |
| x264                | 2 |

A perfect score would be the total of all positive weights. In this case **18**

With this table we can calculate the score of every found subtitle.
All we have to do is check if the subtitle contains a keyword. If it does, the weight assigned to that keyword gets added to the subtitle's score.

For the found subtitles it would look like this:

| Keyword\SubtitleId  | 1 | 2 | 3 | 4 | 5 |
| ---- | ---- | ---- | ---- | ---- | ---- | 
| showname            | x | x |   | x | x |
| s01                 | x | x |   | x | x |
| e01                 | x | x |   | x | x |
| acme                |   | x | x | x |   |
| releasegroupyouhate |   |   |   |   | x |
| 720p                | x |   |   | x | x |
| hdtv                |   | x |   | x | x |
| x264                | x | x |   | x | x |
| **score**           | 7 | 16 | 8 | **18** | -89 |

### Result

The final ordered result is this:

| id    | Subtitles | Score |
| ----- | --------- | ----- |
| 4 | showname.s01.e01.720p.hdtv.x264-acme                | 18 |
| 2 | showname.s01.e01.hdtv.x264-acme                     | 16 |
| 3 | this one should work with acme                      | 8 |
| 1 | showname.s01.e01.720p.bluray.x264-oscorp            | 7 |
| ~~5~~ | ~~showname.s01.e01.720p.hdtv.x264-releasegroupyouhate~~ | ~~-89~~ |

**Comment by phdelodder** [comment]
Thats the way to go! but this would result in more work ... Refactorying every bit of the app to get this result. Changing the GUI of the app and not use number found but score! 

The only thing I would add is that there is a possibility that the user can confirm before download even with 1 100% match.

**Comment by Masterbreel** [comment]
Mijn belangrijkste vraag is eigenlijk, waarom werkte het wel in Jbiersub, en nu niet meer in multisub?

De diagram zit er goed uit, als snap ik het stukje helemaal links boven niet helemaal, maar de rest wel!

Date: Sat, 17 Jan 2015 23:19:42 -0800

**Comment by phdelodder** [comment]
@Masterbreel De reden dat het niet werkt is omdat er teveel aanpassingen zijn gebeurt en dat het voor niet meer duidelijk is om alles goed te krijgen. Dus ipv zitten aanpassen en hopen dat het goed komt, het volledig opnieuw uit werken waardoor alles duidelijker zal worden voor de gebruiker. 

De meeste opmerkingen die ik krijg over de tool is dat het allemaal te complex is, dus simpeler en dat is het voorstel van @RobinHoutevelts .
